### ISSUE TITLE
umm some reason croparia is trying to register a dimention even know it shouldnt

### ISSUE THREAD

**Issue by CharCharthemonkey** [Dalarion/Croparia2.0#1]
im trying to use the mod croparia and for some reason its trying to register dimention 8 as its dimention but i have another mod thats also using that same dimention so is there a way to fix this or no?
[crash-2019-01-10_10.47.14-client.txt](https://github.com/Dalarion/Croparia2.0/files/2746317/crash-2019-01-10_10.47.14-client.txt)
[crash-2019-01-10_10.43.24-client.txt](https://github.com/Dalarion/Croparia2.0/files/2746320/crash-2019-01-10_10.43.24-client.txt)

**Comment by Dalarion** [comment]
Ok, I will check it

**Comment by jkroepke** [comment]
Make the DIM Ids configurable like other mods do it.

**Comment by CharCharthemonkey** [comment]
umm wat? i saw nothing in the mod for dims at all so unless its using an outdated config theres no way to do that exactly

**Comment by jkroepke** [comment]
@CharCharthemonkey No, the message goes to the author. He should add this.

**Comment by CharCharthemonkey** [comment]
ohh ok
