### ISSUE TITLE
Problems about the interaction with Forestry farms

### ISSUE THREAD

**Issue by Prurite** [Dalarion/Croparia2.0#2]
The crops that Croparia added ( like the coal crops ) can't be reaped by Forestry farms.

English is not my first language, please excuse typing errors.

**Comment by Dalarion** [comment]
I will see, I don't know if i can do something like this for the moment

**Comment by Prurite** [comment]
Same issue sent to Forestry.

https://github.com/ForestryMC/ForestryMC/issues/2339

**Comment by Prurite** [comment]
fixed?
