### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by KXIIIS** [Dalarion/Croparia2.0#4]
Hello. This is a suggestion but it's okay if you don't like the idea, or if it can't be done. I've noticed when I farm, I gain way more seeds than I know what to do with. I'm using Croparia along with Mystical Agriculture, and that mod has a seed reprocessor, which basically turns the extra seeds gained into the final product so that you don't end up having a ton of seeds. Would it be possible to make your seeds compatible with the seed reprocessor? It might not be possible, but I thought I'd ask. Thanks so much for your hard work on this mod regardless!

**Comment by Dalarion** [comment]
Hi !
I keep it in mind. But as not everybody plays with Croparia and Mystical Agriculture at the same time, I think that I will create my own way to recycle seeds. 
Thanks a lot for the suggestion !!

**Comment by KXIIIS** [comment]
Alright awesome, and you’re welcome! Can’t wait to see what you do :)
