### ISSUE TITLE
Will you update the source code on github?

### ISSUE THREAD

**Issue by Snapshotlight** [Dalarion/Croparia2.0#6]
Excuse me, I found that you often update mods on Curseforge but you don't update the source code and seldom take a look at Github. Did this project on github died?

**Comment by Snapshotlight** [comment]
the reason why I ask this question is that I want to help translating Croparia into Chinese. Please reply me. I will be with thanks.

**Comment by Dalarion** [comment]
Only a few months later, github has been updated
